# Generated by Django 5.0.2 on 2025-04-05 11:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام شرکت')),
                ('registration_number', models.CharField(max_length=50, verbose_name='شماره ثبت')),
                ('economic_code', models.CharField(max_length=50, verbose_name='کد اقتصادی')),
                ('national_id', models.CharField(max_length=50, verbose_name='شناسه ملی')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('website', models.URLField(blank=True, null=True, verbose_name='وبسایت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='لوگو')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='app2.app2user')),
            ],
            options={
                'verbose_name': 'شرکت',
                'verbose_name_plural': 'شرکت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('registration', 'آگهی تأسیس'), ('statute', 'اساسنامه'), ('license', 'پروانه کسب'), ('tax', 'گواهی مالیات بر ارزش افزوده'), ('insurance', 'گواهی بیمه'), ('other', 'سایر')], max_length=50, verbose_name='نوع سند')),
                ('file', models.FileField(upload_to='company_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='فایل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app2.company')),
            ],
            options={
                'verbose_name': 'سند شرکت',
                'verbose_name_plural': 'اسناد شرکت',
            },
        ),
    ]
