# Generated by Django 5.0.2 on 2025-04-05 11:39

import app2.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_company_companydocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=app2.models.company_logo_path, verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='file',
            field=models.FileField(upload_to=app2.models.company_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='فایل'),
        ),
    ]
