# Generated by Django 5.0.2 on 2025-04-06 11:37

import django.db.models.deletion
import shared_models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_alter_company_logo_alter_companydocument_file'),
        ('shared_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField()),
                ('price_quote', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('proposal_document', models.FileField(upload_to=shared_models.models.application_directory_path)),
                ('additional_document', models.FileField(blank=True, null=True, upload_to=shared_models.models.application_directory_path)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('shortlisted', 'Shortlisted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='app2.company')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='shared_models.tender')),
            ],
            options={
                'unique_together': {('tender', 'applicant')},
            },
        ),
    ]
