# Generated by Django 5.0.2 on 2025-04-06 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_app1user_options_alter_app1user_table_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'permissions': [('can_manage_roles', 'Can manage roles'), ('can_assign_roles', 'Can assign roles to users'), ('can_view_all_roles', 'Can view all roles'), ('can_export_roles', 'Can export roles')], 'verbose_name': 'نقش', 'verbose_name_plural': 'نقش\u200cها'},
        ),
    ]
