# Generated by Django 5.0.2 on 2025-04-06 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_role_options'),
        ('viewflow', '0014_alter_process_parent_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderApplicationProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.process')),
            ],
            options={
                'verbose_name': 'Tender Application Process',
                'verbose_name_plural': 'Tender Application Processes',
            },
            bases=('viewflow.process',),
        ),
    ]
