# Generated by Django 5.0.2 on 2025-04-06 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_tenderapplicationprocess'),
        ('shared_models', '0002_tenderapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderapplicationprocess',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared_models.tenderapplication'),
        ),
    ]
