# Generated by Django 5.0.2 on 2025-04-06 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_tenderapplicationprocess_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelloWorldProcess',
        ),
    ]
