# Generated by Django 5.0.2 on 2025-04-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_delete_helloworldprocess'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'permissions': [('view_page_home', 'Can view home page'), ('view_page_tender_applications', 'Can view tender applications page'), ('view_page_tender_details', 'Can view tender details page'), ('view_page_company_profiles', 'Can view company profiles page'), ('view_page_application_review', 'Can view application review page'), ('view_page_application_execute', 'Can view application execute page'), ('view_page_application_approval', 'Can view application approval page'), ('view_page_technical_evaluation', 'Can view technical evaluation page'), ('view_page_financial_evaluation', 'Can view financial evaluation page'), ('view_page_commercial_evaluation', 'Can view commercial evaluation page'), ('view_page_financial_approval', 'Can view financial approval page'), ('view_page_transaction_approval', 'Can view transaction approval page'), ('view_page_final_decision', 'Can view final decision page'), ('view_page_supplier_management', 'Can view supplier management page'), ('view_page_budget_management', 'Can view budget management page'), ('view_page_role_management', 'Can view role management page'), ('view_page_user_management', 'Can view user management page')], 'verbose_name': 'نقش', 'verbose_name_plural': 'نقش\u200cها'},
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('purchase_expert', 'کارشناس خرید'), ('team_leader', 'سرپرست خرید'), ('supply_chain_manager', 'مدیر زنجیره تامین'), ('technical_evaluator', 'ارزیاب فنی'), ('financial_deputy', 'معاونت مالی و ستادی'), ('financial_manager', 'مدیر مالی'), ('commercial_team_evaluator', 'ارزیاب تیم بازرگانی'), ('financial_team_evaluator', 'ارزیاب تیم مالی'), ('transaction_commission', 'کمیسیون معاملات'), ('ceo', 'مدیر عامل')], max_length=100, verbose_name='نام نقش'),
        ),
    ]
