# Generated by Django 5.0.2 on 2025-04-23 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_role_options_alter_role_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام جریان کار')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('flow_type', models.CharField(choices=[('tender', 'جریان کار مناقصه'), ('purchase', 'جریان کار خرید'), ('approval', 'جریان کار تایید'), ('custom', 'جریان کار سفارشی')], default='custom', max_length=20, verbose_name='نوع جریان کار')),
                ('app_name', models.CharField(help_text='نام برنامه برای استفاده در viewflow', max_length=50, verbose_name='نام برنامه')),
                ('process_class', models.CharField(help_text='نام کلاس فرآیند در models.py', max_length=100, verbose_name='کلاس فرآیند')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('code_generated', models.BooleanField(default=False, verbose_name='کد تولید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_flows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'قالب جریان کار',
                'verbose_name_plural': 'قالب\u200cهای جریان کار',
                'permissions': [('create_flow_template', 'Can create flow template'), ('edit_flow_template', 'Can edit flow template'), ('view_flow_template', 'Can view flow template'), ('delete_flow_template', 'Can delete flow template'), ('generate_flow_code', 'Can generate flow code')],
            },
        ),
        migrations.CreateModel(
            name='FlowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مرحله')),
                ('step_type', models.CharField(choices=[('start', 'شروع'), ('end', 'پایان'), ('view', 'نمایش فرم'), ('function', 'اجرای تابع'), ('if', 'شرط'), ('split', 'انشعاب'), ('join', 'اتصال')], max_length=20, verbose_name='نوع مرحله')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('view_class', models.CharField(blank=True, max_length=100, null=True, verbose_name='کلاس نمایش')),
                ('view_fields', models.TextField(blank=True, null=True, verbose_name='فیلدهای فرم (با کاما جدا شود)')),
                ('function_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام تابع')),
                ('condition_type', models.CharField(blank=True, choices=[('field_check', 'بررسی مقدار فیلد'), ('python_code', 'کد پایتون')], max_length=20, null=True, verbose_name='نوع شرط')),
                ('condition_field', models.CharField(blank=True, max_length=100, null=True, verbose_name='فیلد شرط')),
                ('condition_value', models.CharField(blank=True, max_length=100, null=True, verbose_name='مقدار شرط')),
                ('condition_code', models.TextField(blank=True, null=True, verbose_name='کد شرط')),
                ('permissions', models.CharField(blank=True, max_length=255, null=True, verbose_name='دسترسی\u200cها (با کاما جدا شود)')),
                ('auto_create_permission', models.BooleanField(default=True, verbose_name='ایجاد خودکار دسترسی')),
                ('x_coord', models.IntegerField(default=0, verbose_name='موقعیت X')),
                ('y_coord', models.IntegerField(default=0, verbose_name='موقعیت Y')),
                ('branch_false', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='if_false_source', to='app1.flowstep', verbose_name='مرحله بعدی در صورت نادرست بودن شرط')),
                ('branch_true', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='if_true_source', to='app1.flowstep', verbose_name='مرحله بعدی در صورت درست بودن شرط')),
                ('next_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_steps', to='app1.flowstep', verbose_name='مرحله بعدی')),
                ('flow_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='app1.flowtemplate', verbose_name='قالب جریان کار')),
            ],
            options={
                'verbose_name': 'مرحله جریان کار',
                'verbose_name_plural': 'مراحل جریان کار',
                'ordering': ['flow_template', 'position'],
            },
        ),
    ]
